/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function openWebpage(options?: OpenWebpageOptions | undefined | null): void

export interface OpenWebpageOptions {
  /** The URL to open */
  url: string
  /** The window's title */
  title?: string
  /** If the webpage should be opened fullscreen */
  fullscreen?: boolean
  /** Enables devtools */
  devtools?: boolean
  /** **macOS only** If the titlebar should be hidden */
  titlebarHidden?: boolean
  /** **macOS only** If the window title should be hidden */
  titleHidden?: boolean
}
