/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface OpenWebpageOptions {
  /** The URL to open */
  url?: string
  /** The window's title */
  title?: string
  /** If the webpage should be opened fullscreen */
  fullscreen?: boolean
  /** Enables devtools */
  devtools?: boolean
  /** **macOS only** If the titlebar should be hidden */
  titlebarHidden?: boolean
}
export declare function openWebpage(options?: OpenWebpageOptions | undefined | null): void
