/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export interface OpenWebpageOptions {
  url?: string
  fullscreen?: boolean
}
export declare function openWebpage(options?: OpenWebpageOptions | undefined | null): void
